### ISSUE TITLE
Doesn't work in a Domain Controler

### ISSUE THREAD

**Issue by gustavohellwig** [Simbiat/Anti10016#2]
<img width="981" alt="Screenshot 2022-12-17 at 17 03 23" src="https://user-images.githubusercontent.com/7680647/208245766-4da1da21-c171-4134-93ed-543e9a848b92.png">
Hi,
Thank you for this script, it's awesome.

FYI, it doesn't work if you run it in a domain controller.

**Comment by Simbiat** [comment]
Unfortunately, I do not have access to any domain controllers to even try to test this on them, but the errors says, that it did not find SID `S-1-5-32-544`, which is `Built-in Administrators` group. Most likely this is not related to the fact that you are on a domain controller, but rather that built-in administrator is disabled on it (if I remember correctly, that can be done, not sure if it gets "removed" or just "disabled" from OS perspective, though).  
I would suggest checking what group on the controller is treated as "administrators", get its SID and replace `S-1-5-32-544` in the script with this _proper_ SID.  
That said, I am not sure if I would run this script on any server. At least, not on PROD. While the script itself, should not break anything (as mentioned in #1), if there is a buggy or even malicious software generating the errors, because of lack of permissions, **that** software can break things.

**Comment by mprentice22153** [comment]
I have a version now that works on domain controllers and domain joined member servers

**Comment by Simbiat** [comment]
> I have a version now that works on domain controllers and domain joined member servers

Cool. Feel free to make a PR or share a link to it.

**Comment by gustavohellwig** [comment]
> I have a version now that works on domain controllers and domain joined member servers

Can you share the code please?

**Comment by mprentice22153** [comment]
PR made with my fork. Been tested on a half dozen or so DCs and members. Don't have any standalone servers to test one.

**Comment by Simbiat** [comment]
What's the reasoning for changing log level from Warnings to Errors?
Also on my (non-domain PC) `$administrators.Translate('System.Security.Principal.SecurityIdentifier').Value` fails with `You cannot call a method on a null-valued expression`. I am assuming because `$administrators` is not defined. Or is it a built-in variable, that is supposed to be defined?

**Comment by mprentice22153** [comment]
When we tried it with log level 3 we returned no event log entries. Setting it to 3 returned the logs needed.

I was wondering if that line would break on a non-domain computer. The try-catch at lines 220-224 I thought would handle setting $administrator in either situation. Maybe administrators is set but then it doesn't know how to handle the translation.  Want to work together on the code?

**Comment by Simbiat** [comment]
For the log level, we can use
`$events = Get-WinEvent -FilterHashTable @{ LogName = 'System'; Level = 2,3; Id = 10016 }` and this will cover both warnings and errors, so this is an easy solution.
For `$administrators` we can do
```powershell
try {
    $users.add($administrators.Translate('System.Security.Principal.SecurityIdentifier').Value) | Out-Null
} catch {
    if ($user -ne 'S-1-5-32-544' -and $user_alt -ne 'S-1-5-32-544') {
        $users.Add('S-1-5-32-544') | Out-Null
    }
}
```
but I see you commented out the original `$users.Add('S-1-5-32-544') | Out-Null`. Was it giving an error on domain machines?

**Comment by mprentice22153** [comment]
Is the log level even required in the filter? What you have makes sense. 

Local SIDs do not exist on domain controllers. The BUILTIN\Aministrators group doesn't exist so that SID is not valid and causes an error. The try- catch you have makes sense. It allows domain controllers and members to use the domain group and then everything else can use the local.

**Comment by Simbiat** [comment]
Hm. Considering that filtering has `Id` already, I think you are right and `level` can be safely dropped, so we can use `$events = Get-WinEvent -FilterHashTable @{ LogName = 'System'; Id = 10016 }`. You can update the PR and I will approve it 👍

**Comment by Simbiat** [comment]
Changes from #3 merged. Closing this as resolved.
